name = "ytmusic"
main = "worker.js"
workers_dev = true
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat_v2"]

[[kv_namespaces]]
binding = "YTMUSIC_SITEMAP_KV"
id = "f9dd3de5bd0e45cf96a5158cd1c56a9c"
